# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "spec/**/*"
  DisplayCopNames: true
  RunRailsCops: true

Rails/Output:
  Exclude:
    - "config/unicorn/**/*"

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Style/AccessorMethodName:
  Exclude:
    - "app/controllers/**/*"

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false
