default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: ubuntu
  password:

development:
  <<: *default
  database: circle_test

test:
  <<: *default
  database: circle_test
